
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PlatformFee` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PlatformFee
 * 
 */
export type PlatformFeeModel = runtime.Types.Result.DefaultSelection<Prisma.$PlatformFeePayload>

export type AggregatePlatformFee = {
  _count: PlatformFeeCountAggregateOutputType | null
  _avg: PlatformFeeAvgAggregateOutputType | null
  _sum: PlatformFeeSumAggregateOutputType | null
  _min: PlatformFeeMinAggregateOutputType | null
  _max: PlatformFeeMaxAggregateOutputType | null
}

export type PlatformFeeAvgAggregateOutputType = {
  min_value: number | null
  max_value: number | null
  platform_fee_percentage: runtime.Decimal | null
}

export type PlatformFeeSumAggregateOutputType = {
  min_value: number | null
  max_value: number | null
  platform_fee_percentage: runtime.Decimal | null
}

export type PlatformFeeMinAggregateOutputType = {
  id: string | null
  tier_name: string | null
  min_value: number | null
  max_value: number | null
  platform_fee_percentage: runtime.Decimal | null
  created_at: Date | null
  updated_at: Date | null
}

export type PlatformFeeMaxAggregateOutputType = {
  id: string | null
  tier_name: string | null
  min_value: number | null
  max_value: number | null
  platform_fee_percentage: runtime.Decimal | null
  created_at: Date | null
  updated_at: Date | null
}

export type PlatformFeeCountAggregateOutputType = {
  id: number
  tier_name: number
  min_value: number
  max_value: number
  platform_fee_percentage: number
  created_at: number
  updated_at: number
  _all: number
}


export type PlatformFeeAvgAggregateInputType = {
  min_value?: true
  max_value?: true
  platform_fee_percentage?: true
}

export type PlatformFeeSumAggregateInputType = {
  min_value?: true
  max_value?: true
  platform_fee_percentage?: true
}

export type PlatformFeeMinAggregateInputType = {
  id?: true
  tier_name?: true
  min_value?: true
  max_value?: true
  platform_fee_percentage?: true
  created_at?: true
  updated_at?: true
}

export type PlatformFeeMaxAggregateInputType = {
  id?: true
  tier_name?: true
  min_value?: true
  max_value?: true
  platform_fee_percentage?: true
  created_at?: true
  updated_at?: true
}

export type PlatformFeeCountAggregateInputType = {
  id?: true
  tier_name?: true
  min_value?: true
  max_value?: true
  platform_fee_percentage?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type PlatformFeeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlatformFee to aggregate.
   */
  where?: Prisma.PlatformFeeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlatformFees to fetch.
   */
  orderBy?: Prisma.PlatformFeeOrderByWithRelationInput | Prisma.PlatformFeeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlatformFeeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlatformFees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlatformFees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PlatformFees
  **/
  _count?: true | PlatformFeeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PlatformFeeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PlatformFeeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlatformFeeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlatformFeeMaxAggregateInputType
}

export type GetPlatformFeeAggregateType<T extends PlatformFeeAggregateArgs> = {
      [P in keyof T & keyof AggregatePlatformFee]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlatformFee[P]>
    : Prisma.GetScalarType<T[P], AggregatePlatformFee[P]>
}




export type PlatformFeeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlatformFeeWhereInput
  orderBy?: Prisma.PlatformFeeOrderByWithAggregationInput | Prisma.PlatformFeeOrderByWithAggregationInput[]
  by: Prisma.PlatformFeeScalarFieldEnum[] | Prisma.PlatformFeeScalarFieldEnum
  having?: Prisma.PlatformFeeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlatformFeeCountAggregateInputType | true
  _avg?: PlatformFeeAvgAggregateInputType
  _sum?: PlatformFeeSumAggregateInputType
  _min?: PlatformFeeMinAggregateInputType
  _max?: PlatformFeeMaxAggregateInputType
}

export type PlatformFeeGroupByOutputType = {
  id: string
  tier_name: string
  min_value: number
  max_value: number
  platform_fee_percentage: runtime.Decimal
  created_at: Date
  updated_at: Date
  _count: PlatformFeeCountAggregateOutputType | null
  _avg: PlatformFeeAvgAggregateOutputType | null
  _sum: PlatformFeeSumAggregateOutputType | null
  _min: PlatformFeeMinAggregateOutputType | null
  _max: PlatformFeeMaxAggregateOutputType | null
}

type GetPlatformFeeGroupByPayload<T extends PlatformFeeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlatformFeeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlatformFeeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlatformFeeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlatformFeeGroupByOutputType[P]>
      }
    >
  >



export type PlatformFeeWhereInput = {
  AND?: Prisma.PlatformFeeWhereInput | Prisma.PlatformFeeWhereInput[]
  OR?: Prisma.PlatformFeeWhereInput[]
  NOT?: Prisma.PlatformFeeWhereInput | Prisma.PlatformFeeWhereInput[]
  id?: Prisma.StringFilter<"PlatformFee"> | string
  tier_name?: Prisma.StringFilter<"PlatformFee"> | string
  min_value?: Prisma.IntFilter<"PlatformFee"> | number
  max_value?: Prisma.IntFilter<"PlatformFee"> | number
  platform_fee_percentage?: Prisma.DecimalFilter<"PlatformFee"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  created_at?: Prisma.DateTimeFilter<"PlatformFee"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"PlatformFee"> | Date | string
}

export type PlatformFeeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tier_name?: Prisma.SortOrder
  min_value?: Prisma.SortOrder
  max_value?: Prisma.SortOrder
  platform_fee_percentage?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type PlatformFeeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PlatformFeeWhereInput | Prisma.PlatformFeeWhereInput[]
  OR?: Prisma.PlatformFeeWhereInput[]
  NOT?: Prisma.PlatformFeeWhereInput | Prisma.PlatformFeeWhereInput[]
  tier_name?: Prisma.StringFilter<"PlatformFee"> | string
  min_value?: Prisma.IntFilter<"PlatformFee"> | number
  max_value?: Prisma.IntFilter<"PlatformFee"> | number
  platform_fee_percentage?: Prisma.DecimalFilter<"PlatformFee"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  created_at?: Prisma.DateTimeFilter<"PlatformFee"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"PlatformFee"> | Date | string
}, "id">

export type PlatformFeeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tier_name?: Prisma.SortOrder
  min_value?: Prisma.SortOrder
  max_value?: Prisma.SortOrder
  platform_fee_percentage?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.PlatformFeeCountOrderByAggregateInput
  _avg?: Prisma.PlatformFeeAvgOrderByAggregateInput
  _max?: Prisma.PlatformFeeMaxOrderByAggregateInput
  _min?: Prisma.PlatformFeeMinOrderByAggregateInput
  _sum?: Prisma.PlatformFeeSumOrderByAggregateInput
}

export type PlatformFeeScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlatformFeeScalarWhereWithAggregatesInput | Prisma.PlatformFeeScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlatformFeeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlatformFeeScalarWhereWithAggregatesInput | Prisma.PlatformFeeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PlatformFee"> | string
  tier_name?: Prisma.StringWithAggregatesFilter<"PlatformFee"> | string
  min_value?: Prisma.IntWithAggregatesFilter<"PlatformFee"> | number
  max_value?: Prisma.IntWithAggregatesFilter<"PlatformFee"> | number
  platform_fee_percentage?: Prisma.DecimalWithAggregatesFilter<"PlatformFee"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"PlatformFee"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"PlatformFee"> | Date | string
}

export type PlatformFeeCreateInput = {
  id?: string
  tier_name: string
  min_value?: number
  max_value?: number
  platform_fee_percentage: runtime.Decimal | runtime.DecimalJsLike | number | string
  created_at?: Date | string
  updated_at?: Date | string
}

export type PlatformFeeUncheckedCreateInput = {
  id?: string
  tier_name: string
  min_value?: number
  max_value?: number
  platform_fee_percentage: runtime.Decimal | runtime.DecimalJsLike | number | string
  created_at?: Date | string
  updated_at?: Date | string
}

export type PlatformFeeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tier_name?: Prisma.StringFieldUpdateOperationsInput | string
  min_value?: Prisma.IntFieldUpdateOperationsInput | number
  max_value?: Prisma.IntFieldUpdateOperationsInput | number
  platform_fee_percentage?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlatformFeeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tier_name?: Prisma.StringFieldUpdateOperationsInput | string
  min_value?: Prisma.IntFieldUpdateOperationsInput | number
  max_value?: Prisma.IntFieldUpdateOperationsInput | number
  platform_fee_percentage?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlatformFeeCreateManyInput = {
  id?: string
  tier_name: string
  min_value?: number
  max_value?: number
  platform_fee_percentage: runtime.Decimal | runtime.DecimalJsLike | number | string
  created_at?: Date | string
  updated_at?: Date | string
}

export type PlatformFeeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tier_name?: Prisma.StringFieldUpdateOperationsInput | string
  min_value?: Prisma.IntFieldUpdateOperationsInput | number
  max_value?: Prisma.IntFieldUpdateOperationsInput | number
  platform_fee_percentage?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlatformFeeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tier_name?: Prisma.StringFieldUpdateOperationsInput | string
  min_value?: Prisma.IntFieldUpdateOperationsInput | number
  max_value?: Prisma.IntFieldUpdateOperationsInput | number
  platform_fee_percentage?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlatformFeeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tier_name?: Prisma.SortOrder
  min_value?: Prisma.SortOrder
  max_value?: Prisma.SortOrder
  platform_fee_percentage?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type PlatformFeeAvgOrderByAggregateInput = {
  min_value?: Prisma.SortOrder
  max_value?: Prisma.SortOrder
  platform_fee_percentage?: Prisma.SortOrder
}

export type PlatformFeeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tier_name?: Prisma.SortOrder
  min_value?: Prisma.SortOrder
  max_value?: Prisma.SortOrder
  platform_fee_percentage?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type PlatformFeeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tier_name?: Prisma.SortOrder
  min_value?: Prisma.SortOrder
  max_value?: Prisma.SortOrder
  platform_fee_percentage?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type PlatformFeeSumOrderByAggregateInput = {
  min_value?: Prisma.SortOrder
  max_value?: Prisma.SortOrder
  platform_fee_percentage?: Prisma.SortOrder
}

export type DecimalFieldUpdateOperationsInput = {
  set?: runtime.Decimal | runtime.DecimalJsLike | number | string
  increment?: runtime.Decimal | runtime.DecimalJsLike | number | string
  decrement?: runtime.Decimal | runtime.DecimalJsLike | number | string
  multiply?: runtime.Decimal | runtime.DecimalJsLike | number | string
  divide?: runtime.Decimal | runtime.DecimalJsLike | number | string
}



export type PlatformFeeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tier_name?: boolean
  min_value?: boolean
  max_value?: boolean
  platform_fee_percentage?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["platformFee"]>

export type PlatformFeeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tier_name?: boolean
  min_value?: boolean
  max_value?: boolean
  platform_fee_percentage?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["platformFee"]>

export type PlatformFeeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tier_name?: boolean
  min_value?: boolean
  max_value?: boolean
  platform_fee_percentage?: boolean
  created_at?: boolean
  updated_at?: boolean
}, ExtArgs["result"]["platformFee"]>

export type PlatformFeeSelectScalar = {
  id?: boolean
  tier_name?: boolean
  min_value?: boolean
  max_value?: boolean
  platform_fee_percentage?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type PlatformFeeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tier_name" | "min_value" | "max_value" | "platform_fee_percentage" | "created_at" | "updated_at", ExtArgs["result"]["platformFee"]>

export type $PlatformFeePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PlatformFee"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tier_name: string
    min_value: number
    max_value: number
    platform_fee_percentage: runtime.Decimal
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["platformFee"]>
  composites: {}
}

export type PlatformFeeGetPayload<S extends boolean | null | undefined | PlatformFeeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlatformFeePayload, S>

export type PlatformFeeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlatformFeeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlatformFeeCountAggregateInputType | true
  }

export interface PlatformFeeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PlatformFee'], meta: { name: 'PlatformFee' } }
  /**
   * Find zero or one PlatformFee that matches the filter.
   * @param {PlatformFeeFindUniqueArgs} args - Arguments to find a PlatformFee
   * @example
   * // Get one PlatformFee
   * const platformFee = await prisma.platformFee.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlatformFeeFindUniqueArgs>(args: Prisma.SelectSubset<T, PlatformFeeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlatformFeeClient<runtime.Types.Result.GetResult<Prisma.$PlatformFeePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PlatformFee that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlatformFeeFindUniqueOrThrowArgs} args - Arguments to find a PlatformFee
   * @example
   * // Get one PlatformFee
   * const platformFee = await prisma.platformFee.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlatformFeeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlatformFeeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlatformFeeClient<runtime.Types.Result.GetResult<Prisma.$PlatformFeePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlatformFee that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformFeeFindFirstArgs} args - Arguments to find a PlatformFee
   * @example
   * // Get one PlatformFee
   * const platformFee = await prisma.platformFee.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlatformFeeFindFirstArgs>(args?: Prisma.SelectSubset<T, PlatformFeeFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlatformFeeClient<runtime.Types.Result.GetResult<Prisma.$PlatformFeePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlatformFee that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformFeeFindFirstOrThrowArgs} args - Arguments to find a PlatformFee
   * @example
   * // Get one PlatformFee
   * const platformFee = await prisma.platformFee.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlatformFeeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlatformFeeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlatformFeeClient<runtime.Types.Result.GetResult<Prisma.$PlatformFeePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PlatformFees that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformFeeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PlatformFees
   * const platformFees = await prisma.platformFee.findMany()
   * 
   * // Get first 10 PlatformFees
   * const platformFees = await prisma.platformFee.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const platformFeeWithIdOnly = await prisma.platformFee.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PlatformFeeFindManyArgs>(args?: Prisma.SelectSubset<T, PlatformFeeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlatformFeePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PlatformFee.
   * @param {PlatformFeeCreateArgs} args - Arguments to create a PlatformFee.
   * @example
   * // Create one PlatformFee
   * const PlatformFee = await prisma.platformFee.create({
   *   data: {
   *     // ... data to create a PlatformFee
   *   }
   * })
   * 
   */
  create<T extends PlatformFeeCreateArgs>(args: Prisma.SelectSubset<T, PlatformFeeCreateArgs<ExtArgs>>): Prisma.Prisma__PlatformFeeClient<runtime.Types.Result.GetResult<Prisma.$PlatformFeePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PlatformFees.
   * @param {PlatformFeeCreateManyArgs} args - Arguments to create many PlatformFees.
   * @example
   * // Create many PlatformFees
   * const platformFee = await prisma.platformFee.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlatformFeeCreateManyArgs>(args?: Prisma.SelectSubset<T, PlatformFeeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PlatformFees and returns the data saved in the database.
   * @param {PlatformFeeCreateManyAndReturnArgs} args - Arguments to create many PlatformFees.
   * @example
   * // Create many PlatformFees
   * const platformFee = await prisma.platformFee.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PlatformFees and only return the `id`
   * const platformFeeWithIdOnly = await prisma.platformFee.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlatformFeeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlatformFeeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlatformFeePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PlatformFee.
   * @param {PlatformFeeDeleteArgs} args - Arguments to delete one PlatformFee.
   * @example
   * // Delete one PlatformFee
   * const PlatformFee = await prisma.platformFee.delete({
   *   where: {
   *     // ... filter to delete one PlatformFee
   *   }
   * })
   * 
   */
  delete<T extends PlatformFeeDeleteArgs>(args: Prisma.SelectSubset<T, PlatformFeeDeleteArgs<ExtArgs>>): Prisma.Prisma__PlatformFeeClient<runtime.Types.Result.GetResult<Prisma.$PlatformFeePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PlatformFee.
   * @param {PlatformFeeUpdateArgs} args - Arguments to update one PlatformFee.
   * @example
   * // Update one PlatformFee
   * const platformFee = await prisma.platformFee.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlatformFeeUpdateArgs>(args: Prisma.SelectSubset<T, PlatformFeeUpdateArgs<ExtArgs>>): Prisma.Prisma__PlatformFeeClient<runtime.Types.Result.GetResult<Prisma.$PlatformFeePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PlatformFees.
   * @param {PlatformFeeDeleteManyArgs} args - Arguments to filter PlatformFees to delete.
   * @example
   * // Delete a few PlatformFees
   * const { count } = await prisma.platformFee.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlatformFeeDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlatformFeeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlatformFees.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformFeeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PlatformFees
   * const platformFee = await prisma.platformFee.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlatformFeeUpdateManyArgs>(args: Prisma.SelectSubset<T, PlatformFeeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlatformFees and returns the data updated in the database.
   * @param {PlatformFeeUpdateManyAndReturnArgs} args - Arguments to update many PlatformFees.
   * @example
   * // Update many PlatformFees
   * const platformFee = await prisma.platformFee.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PlatformFees and only return the `id`
   * const platformFeeWithIdOnly = await prisma.platformFee.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlatformFeeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlatformFeeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlatformFeePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PlatformFee.
   * @param {PlatformFeeUpsertArgs} args - Arguments to update or create a PlatformFee.
   * @example
   * // Update or create a PlatformFee
   * const platformFee = await prisma.platformFee.upsert({
   *   create: {
   *     // ... data to create a PlatformFee
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PlatformFee we want to update
   *   }
   * })
   */
  upsert<T extends PlatformFeeUpsertArgs>(args: Prisma.SelectSubset<T, PlatformFeeUpsertArgs<ExtArgs>>): Prisma.Prisma__PlatformFeeClient<runtime.Types.Result.GetResult<Prisma.$PlatformFeePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PlatformFees.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformFeeCountArgs} args - Arguments to filter PlatformFees to count.
   * @example
   * // Count the number of PlatformFees
   * const count = await prisma.platformFee.count({
   *   where: {
   *     // ... the filter for the PlatformFees we want to count
   *   }
   * })
  **/
  count<T extends PlatformFeeCountArgs>(
    args?: Prisma.Subset<T, PlatformFeeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlatformFeeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PlatformFee.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformFeeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlatformFeeAggregateArgs>(args: Prisma.Subset<T, PlatformFeeAggregateArgs>): Prisma.PrismaPromise<GetPlatformFeeAggregateType<T>>

  /**
   * Group by PlatformFee.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlatformFeeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlatformFeeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlatformFeeGroupByArgs['orderBy'] }
      : { orderBy?: PlatformFeeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlatformFeeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlatformFeeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PlatformFee model
 */
readonly fields: PlatformFeeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PlatformFee.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlatformFeeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PlatformFee model
 */
export interface PlatformFeeFieldRefs {
  readonly id: Prisma.FieldRef<"PlatformFee", 'String'>
  readonly tier_name: Prisma.FieldRef<"PlatformFee", 'String'>
  readonly min_value: Prisma.FieldRef<"PlatformFee", 'Int'>
  readonly max_value: Prisma.FieldRef<"PlatformFee", 'Int'>
  readonly platform_fee_percentage: Prisma.FieldRef<"PlatformFee", 'Decimal'>
  readonly created_at: Prisma.FieldRef<"PlatformFee", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"PlatformFee", 'DateTime'>
}
    

// Custom InputTypes
/**
 * PlatformFee findUnique
 */
export type PlatformFeeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformFee
   */
  select?: Prisma.PlatformFeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformFee
   */
  omit?: Prisma.PlatformFeeOmit<ExtArgs> | null
  /**
   * Filter, which PlatformFee to fetch.
   */
  where: Prisma.PlatformFeeWhereUniqueInput
}

/**
 * PlatformFee findUniqueOrThrow
 */
export type PlatformFeeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformFee
   */
  select?: Prisma.PlatformFeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformFee
   */
  omit?: Prisma.PlatformFeeOmit<ExtArgs> | null
  /**
   * Filter, which PlatformFee to fetch.
   */
  where: Prisma.PlatformFeeWhereUniqueInput
}

/**
 * PlatformFee findFirst
 */
export type PlatformFeeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformFee
   */
  select?: Prisma.PlatformFeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformFee
   */
  omit?: Prisma.PlatformFeeOmit<ExtArgs> | null
  /**
   * Filter, which PlatformFee to fetch.
   */
  where?: Prisma.PlatformFeeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlatformFees to fetch.
   */
  orderBy?: Prisma.PlatformFeeOrderByWithRelationInput | Prisma.PlatformFeeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlatformFees.
   */
  cursor?: Prisma.PlatformFeeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlatformFees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlatformFees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlatformFees.
   */
  distinct?: Prisma.PlatformFeeScalarFieldEnum | Prisma.PlatformFeeScalarFieldEnum[]
}

/**
 * PlatformFee findFirstOrThrow
 */
export type PlatformFeeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformFee
   */
  select?: Prisma.PlatformFeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformFee
   */
  omit?: Prisma.PlatformFeeOmit<ExtArgs> | null
  /**
   * Filter, which PlatformFee to fetch.
   */
  where?: Prisma.PlatformFeeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlatformFees to fetch.
   */
  orderBy?: Prisma.PlatformFeeOrderByWithRelationInput | Prisma.PlatformFeeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlatformFees.
   */
  cursor?: Prisma.PlatformFeeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlatformFees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlatformFees.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlatformFees.
   */
  distinct?: Prisma.PlatformFeeScalarFieldEnum | Prisma.PlatformFeeScalarFieldEnum[]
}

/**
 * PlatformFee findMany
 */
export type PlatformFeeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformFee
   */
  select?: Prisma.PlatformFeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformFee
   */
  omit?: Prisma.PlatformFeeOmit<ExtArgs> | null
  /**
   * Filter, which PlatformFees to fetch.
   */
  where?: Prisma.PlatformFeeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlatformFees to fetch.
   */
  orderBy?: Prisma.PlatformFeeOrderByWithRelationInput | Prisma.PlatformFeeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PlatformFees.
   */
  cursor?: Prisma.PlatformFeeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlatformFees from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlatformFees.
   */
  skip?: number
  distinct?: Prisma.PlatformFeeScalarFieldEnum | Prisma.PlatformFeeScalarFieldEnum[]
}

/**
 * PlatformFee create
 */
export type PlatformFeeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformFee
   */
  select?: Prisma.PlatformFeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformFee
   */
  omit?: Prisma.PlatformFeeOmit<ExtArgs> | null
  /**
   * The data needed to create a PlatformFee.
   */
  data: Prisma.XOR<Prisma.PlatformFeeCreateInput, Prisma.PlatformFeeUncheckedCreateInput>
}

/**
 * PlatformFee createMany
 */
export type PlatformFeeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PlatformFees.
   */
  data: Prisma.PlatformFeeCreateManyInput | Prisma.PlatformFeeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PlatformFee createManyAndReturn
 */
export type PlatformFeeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformFee
   */
  select?: Prisma.PlatformFeeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformFee
   */
  omit?: Prisma.PlatformFeeOmit<ExtArgs> | null
  /**
   * The data used to create many PlatformFees.
   */
  data: Prisma.PlatformFeeCreateManyInput | Prisma.PlatformFeeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PlatformFee update
 */
export type PlatformFeeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformFee
   */
  select?: Prisma.PlatformFeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformFee
   */
  omit?: Prisma.PlatformFeeOmit<ExtArgs> | null
  /**
   * The data needed to update a PlatformFee.
   */
  data: Prisma.XOR<Prisma.PlatformFeeUpdateInput, Prisma.PlatformFeeUncheckedUpdateInput>
  /**
   * Choose, which PlatformFee to update.
   */
  where: Prisma.PlatformFeeWhereUniqueInput
}

/**
 * PlatformFee updateMany
 */
export type PlatformFeeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PlatformFees.
   */
  data: Prisma.XOR<Prisma.PlatformFeeUpdateManyMutationInput, Prisma.PlatformFeeUncheckedUpdateManyInput>
  /**
   * Filter which PlatformFees to update
   */
  where?: Prisma.PlatformFeeWhereInput
  /**
   * Limit how many PlatformFees to update.
   */
  limit?: number
}

/**
 * PlatformFee updateManyAndReturn
 */
export type PlatformFeeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformFee
   */
  select?: Prisma.PlatformFeeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformFee
   */
  omit?: Prisma.PlatformFeeOmit<ExtArgs> | null
  /**
   * The data used to update PlatformFees.
   */
  data: Prisma.XOR<Prisma.PlatformFeeUpdateManyMutationInput, Prisma.PlatformFeeUncheckedUpdateManyInput>
  /**
   * Filter which PlatformFees to update
   */
  where?: Prisma.PlatformFeeWhereInput
  /**
   * Limit how many PlatformFees to update.
   */
  limit?: number
}

/**
 * PlatformFee upsert
 */
export type PlatformFeeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformFee
   */
  select?: Prisma.PlatformFeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformFee
   */
  omit?: Prisma.PlatformFeeOmit<ExtArgs> | null
  /**
   * The filter to search for the PlatformFee to update in case it exists.
   */
  where: Prisma.PlatformFeeWhereUniqueInput
  /**
   * In case the PlatformFee found by the `where` argument doesn't exist, create a new PlatformFee with this data.
   */
  create: Prisma.XOR<Prisma.PlatformFeeCreateInput, Prisma.PlatformFeeUncheckedCreateInput>
  /**
   * In case the PlatformFee was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlatformFeeUpdateInput, Prisma.PlatformFeeUncheckedUpdateInput>
}

/**
 * PlatformFee delete
 */
export type PlatformFeeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformFee
   */
  select?: Prisma.PlatformFeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformFee
   */
  omit?: Prisma.PlatformFeeOmit<ExtArgs> | null
  /**
   * Filter which PlatformFee to delete.
   */
  where: Prisma.PlatformFeeWhereUniqueInput
}

/**
 * PlatformFee deleteMany
 */
export type PlatformFeeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlatformFees to delete
   */
  where?: Prisma.PlatformFeeWhereInput
  /**
   * Limit how many PlatformFees to delete.
   */
  limit?: number
}

/**
 * PlatformFee without action
 */
export type PlatformFeeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlatformFee
   */
  select?: Prisma.PlatformFeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlatformFee
   */
  omit?: Prisma.PlatformFeeOmit<ExtArgs> | null
}
