
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ServiceOfferings` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ServiceOfferings
 * 
 */
export type ServiceOfferingsModel = runtime.Types.Result.DefaultSelection<Prisma.$ServiceOfferingsPayload>

export type AggregateServiceOfferings = {
  _count: ServiceOfferingsCountAggregateOutputType | null
  _min: ServiceOfferingsMinAggregateOutputType | null
  _max: ServiceOfferingsMaxAggregateOutputType | null
}

export type ServiceOfferingsMinAggregateOutputType = {
  id: string | null
  specialistId: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type ServiceOfferingsMaxAggregateOutputType = {
  id: string | null
  specialistId: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type ServiceOfferingsCountAggregateOutputType = {
  id: number
  specialistId: number
  created_at: number
  updated_at: number
  _all: number
}


export type ServiceOfferingsMinAggregateInputType = {
  id?: true
  specialistId?: true
  created_at?: true
  updated_at?: true
}

export type ServiceOfferingsMaxAggregateInputType = {
  id?: true
  specialistId?: true
  created_at?: true
  updated_at?: true
}

export type ServiceOfferingsCountAggregateInputType = {
  id?: true
  specialistId?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type ServiceOfferingsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceOfferings to aggregate.
   */
  where?: Prisma.ServiceOfferingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceOfferings to fetch.
   */
  orderBy?: Prisma.ServiceOfferingsOrderByWithRelationInput | Prisma.ServiceOfferingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ServiceOfferingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceOfferings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceOfferings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ServiceOfferings
  **/
  _count?: true | ServiceOfferingsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServiceOfferingsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServiceOfferingsMaxAggregateInputType
}

export type GetServiceOfferingsAggregateType<T extends ServiceOfferingsAggregateArgs> = {
      [P in keyof T & keyof AggregateServiceOfferings]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServiceOfferings[P]>
    : Prisma.GetScalarType<T[P], AggregateServiceOfferings[P]>
}




export type ServiceOfferingsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceOfferingsWhereInput
  orderBy?: Prisma.ServiceOfferingsOrderByWithAggregationInput | Prisma.ServiceOfferingsOrderByWithAggregationInput[]
  by: Prisma.ServiceOfferingsScalarFieldEnum[] | Prisma.ServiceOfferingsScalarFieldEnum
  having?: Prisma.ServiceOfferingsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServiceOfferingsCountAggregateInputType | true
  _min?: ServiceOfferingsMinAggregateInputType
  _max?: ServiceOfferingsMaxAggregateInputType
}

export type ServiceOfferingsGroupByOutputType = {
  id: string
  specialistId: string
  created_at: Date
  updated_at: Date
  _count: ServiceOfferingsCountAggregateOutputType | null
  _min: ServiceOfferingsMinAggregateOutputType | null
  _max: ServiceOfferingsMaxAggregateOutputType | null
}

type GetServiceOfferingsGroupByPayload<T extends ServiceOfferingsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServiceOfferingsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServiceOfferingsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServiceOfferingsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServiceOfferingsGroupByOutputType[P]>
      }
    >
  >



export type ServiceOfferingsWhereInput = {
  AND?: Prisma.ServiceOfferingsWhereInput | Prisma.ServiceOfferingsWhereInput[]
  OR?: Prisma.ServiceOfferingsWhereInput[]
  NOT?: Prisma.ServiceOfferingsWhereInput | Prisma.ServiceOfferingsWhereInput[]
  id?: Prisma.StringFilter<"ServiceOfferings"> | string
  specialistId?: Prisma.StringFilter<"ServiceOfferings"> | string
  created_at?: Prisma.DateTimeFilter<"ServiceOfferings"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"ServiceOfferings"> | Date | string
  specialists?: Prisma.XOR<Prisma.SpecialistScalarRelationFilter, Prisma.SpecialistWhereInput>
}

export type ServiceOfferingsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  specialistId?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  specialists?: Prisma.SpecialistOrderByWithRelationInput
}

export type ServiceOfferingsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ServiceOfferingsWhereInput | Prisma.ServiceOfferingsWhereInput[]
  OR?: Prisma.ServiceOfferingsWhereInput[]
  NOT?: Prisma.ServiceOfferingsWhereInput | Prisma.ServiceOfferingsWhereInput[]
  specialistId?: Prisma.StringFilter<"ServiceOfferings"> | string
  created_at?: Prisma.DateTimeFilter<"ServiceOfferings"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"ServiceOfferings"> | Date | string
  specialists?: Prisma.XOR<Prisma.SpecialistScalarRelationFilter, Prisma.SpecialistWhereInput>
}, "id">

export type ServiceOfferingsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  specialistId?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.ServiceOfferingsCountOrderByAggregateInput
  _max?: Prisma.ServiceOfferingsMaxOrderByAggregateInput
  _min?: Prisma.ServiceOfferingsMinOrderByAggregateInput
}

export type ServiceOfferingsScalarWhereWithAggregatesInput = {
  AND?: Prisma.ServiceOfferingsScalarWhereWithAggregatesInput | Prisma.ServiceOfferingsScalarWhereWithAggregatesInput[]
  OR?: Prisma.ServiceOfferingsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ServiceOfferingsScalarWhereWithAggregatesInput | Prisma.ServiceOfferingsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ServiceOfferings"> | string
  specialistId?: Prisma.StringWithAggregatesFilter<"ServiceOfferings"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"ServiceOfferings"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"ServiceOfferings"> | Date | string
}

export type ServiceOfferingsCreateInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
  specialists: Prisma.SpecialistCreateNestedOneWithoutService_offeringsInput
}

export type ServiceOfferingsUncheckedCreateInput = {
  id?: string
  specialistId: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type ServiceOfferingsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  specialists?: Prisma.SpecialistUpdateOneRequiredWithoutService_offeringsNestedInput
}

export type ServiceOfferingsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  specialistId?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceOfferingsCreateManyInput = {
  id?: string
  specialistId: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type ServiceOfferingsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceOfferingsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  specialistId?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceOfferingsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  specialistId?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ServiceOfferingsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  specialistId?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ServiceOfferingsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  specialistId?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ServiceOfferingsListRelationFilter = {
  every?: Prisma.ServiceOfferingsWhereInput
  some?: Prisma.ServiceOfferingsWhereInput
  none?: Prisma.ServiceOfferingsWhereInput
}

export type ServiceOfferingsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ServiceOfferingsCreateNestedManyWithoutSpecialistsInput = {
  create?: Prisma.XOR<Prisma.ServiceOfferingsCreateWithoutSpecialistsInput, Prisma.ServiceOfferingsUncheckedCreateWithoutSpecialistsInput> | Prisma.ServiceOfferingsCreateWithoutSpecialistsInput[] | Prisma.ServiceOfferingsUncheckedCreateWithoutSpecialistsInput[]
  connectOrCreate?: Prisma.ServiceOfferingsCreateOrConnectWithoutSpecialistsInput | Prisma.ServiceOfferingsCreateOrConnectWithoutSpecialistsInput[]
  createMany?: Prisma.ServiceOfferingsCreateManySpecialistsInputEnvelope
  connect?: Prisma.ServiceOfferingsWhereUniqueInput | Prisma.ServiceOfferingsWhereUniqueInput[]
}

export type ServiceOfferingsUncheckedCreateNestedManyWithoutSpecialistsInput = {
  create?: Prisma.XOR<Prisma.ServiceOfferingsCreateWithoutSpecialistsInput, Prisma.ServiceOfferingsUncheckedCreateWithoutSpecialistsInput> | Prisma.ServiceOfferingsCreateWithoutSpecialistsInput[] | Prisma.ServiceOfferingsUncheckedCreateWithoutSpecialistsInput[]
  connectOrCreate?: Prisma.ServiceOfferingsCreateOrConnectWithoutSpecialistsInput | Prisma.ServiceOfferingsCreateOrConnectWithoutSpecialistsInput[]
  createMany?: Prisma.ServiceOfferingsCreateManySpecialistsInputEnvelope
  connect?: Prisma.ServiceOfferingsWhereUniqueInput | Prisma.ServiceOfferingsWhereUniqueInput[]
}

export type ServiceOfferingsUpdateManyWithoutSpecialistsNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceOfferingsCreateWithoutSpecialistsInput, Prisma.ServiceOfferingsUncheckedCreateWithoutSpecialistsInput> | Prisma.ServiceOfferingsCreateWithoutSpecialistsInput[] | Prisma.ServiceOfferingsUncheckedCreateWithoutSpecialistsInput[]
  connectOrCreate?: Prisma.ServiceOfferingsCreateOrConnectWithoutSpecialistsInput | Prisma.ServiceOfferingsCreateOrConnectWithoutSpecialistsInput[]
  upsert?: Prisma.ServiceOfferingsUpsertWithWhereUniqueWithoutSpecialistsInput | Prisma.ServiceOfferingsUpsertWithWhereUniqueWithoutSpecialistsInput[]
  createMany?: Prisma.ServiceOfferingsCreateManySpecialistsInputEnvelope
  set?: Prisma.ServiceOfferingsWhereUniqueInput | Prisma.ServiceOfferingsWhereUniqueInput[]
  disconnect?: Prisma.ServiceOfferingsWhereUniqueInput | Prisma.ServiceOfferingsWhereUniqueInput[]
  delete?: Prisma.ServiceOfferingsWhereUniqueInput | Prisma.ServiceOfferingsWhereUniqueInput[]
  connect?: Prisma.ServiceOfferingsWhereUniqueInput | Prisma.ServiceOfferingsWhereUniqueInput[]
  update?: Prisma.ServiceOfferingsUpdateWithWhereUniqueWithoutSpecialistsInput | Prisma.ServiceOfferingsUpdateWithWhereUniqueWithoutSpecialistsInput[]
  updateMany?: Prisma.ServiceOfferingsUpdateManyWithWhereWithoutSpecialistsInput | Prisma.ServiceOfferingsUpdateManyWithWhereWithoutSpecialistsInput[]
  deleteMany?: Prisma.ServiceOfferingsScalarWhereInput | Prisma.ServiceOfferingsScalarWhereInput[]
}

export type ServiceOfferingsUncheckedUpdateManyWithoutSpecialistsNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceOfferingsCreateWithoutSpecialistsInput, Prisma.ServiceOfferingsUncheckedCreateWithoutSpecialistsInput> | Prisma.ServiceOfferingsCreateWithoutSpecialistsInput[] | Prisma.ServiceOfferingsUncheckedCreateWithoutSpecialistsInput[]
  connectOrCreate?: Prisma.ServiceOfferingsCreateOrConnectWithoutSpecialistsInput | Prisma.ServiceOfferingsCreateOrConnectWithoutSpecialistsInput[]
  upsert?: Prisma.ServiceOfferingsUpsertWithWhereUniqueWithoutSpecialistsInput | Prisma.ServiceOfferingsUpsertWithWhereUniqueWithoutSpecialistsInput[]
  createMany?: Prisma.ServiceOfferingsCreateManySpecialistsInputEnvelope
  set?: Prisma.ServiceOfferingsWhereUniqueInput | Prisma.ServiceOfferingsWhereUniqueInput[]
  disconnect?: Prisma.ServiceOfferingsWhereUniqueInput | Prisma.ServiceOfferingsWhereUniqueInput[]
  delete?: Prisma.ServiceOfferingsWhereUniqueInput | Prisma.ServiceOfferingsWhereUniqueInput[]
  connect?: Prisma.ServiceOfferingsWhereUniqueInput | Prisma.ServiceOfferingsWhereUniqueInput[]
  update?: Prisma.ServiceOfferingsUpdateWithWhereUniqueWithoutSpecialistsInput | Prisma.ServiceOfferingsUpdateWithWhereUniqueWithoutSpecialistsInput[]
  updateMany?: Prisma.ServiceOfferingsUpdateManyWithWhereWithoutSpecialistsInput | Prisma.ServiceOfferingsUpdateManyWithWhereWithoutSpecialistsInput[]
  deleteMany?: Prisma.ServiceOfferingsScalarWhereInput | Prisma.ServiceOfferingsScalarWhereInput[]
}

export type ServiceOfferingsCreateWithoutSpecialistsInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type ServiceOfferingsUncheckedCreateWithoutSpecialistsInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type ServiceOfferingsCreateOrConnectWithoutSpecialistsInput = {
  where: Prisma.ServiceOfferingsWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceOfferingsCreateWithoutSpecialistsInput, Prisma.ServiceOfferingsUncheckedCreateWithoutSpecialistsInput>
}

export type ServiceOfferingsCreateManySpecialistsInputEnvelope = {
  data: Prisma.ServiceOfferingsCreateManySpecialistsInput | Prisma.ServiceOfferingsCreateManySpecialistsInput[]
  skipDuplicates?: boolean
}

export type ServiceOfferingsUpsertWithWhereUniqueWithoutSpecialistsInput = {
  where: Prisma.ServiceOfferingsWhereUniqueInput
  update: Prisma.XOR<Prisma.ServiceOfferingsUpdateWithoutSpecialistsInput, Prisma.ServiceOfferingsUncheckedUpdateWithoutSpecialistsInput>
  create: Prisma.XOR<Prisma.ServiceOfferingsCreateWithoutSpecialistsInput, Prisma.ServiceOfferingsUncheckedCreateWithoutSpecialistsInput>
}

export type ServiceOfferingsUpdateWithWhereUniqueWithoutSpecialistsInput = {
  where: Prisma.ServiceOfferingsWhereUniqueInput
  data: Prisma.XOR<Prisma.ServiceOfferingsUpdateWithoutSpecialistsInput, Prisma.ServiceOfferingsUncheckedUpdateWithoutSpecialistsInput>
}

export type ServiceOfferingsUpdateManyWithWhereWithoutSpecialistsInput = {
  where: Prisma.ServiceOfferingsScalarWhereInput
  data: Prisma.XOR<Prisma.ServiceOfferingsUpdateManyMutationInput, Prisma.ServiceOfferingsUncheckedUpdateManyWithoutSpecialistsInput>
}

export type ServiceOfferingsScalarWhereInput = {
  AND?: Prisma.ServiceOfferingsScalarWhereInput | Prisma.ServiceOfferingsScalarWhereInput[]
  OR?: Prisma.ServiceOfferingsScalarWhereInput[]
  NOT?: Prisma.ServiceOfferingsScalarWhereInput | Prisma.ServiceOfferingsScalarWhereInput[]
  id?: Prisma.StringFilter<"ServiceOfferings"> | string
  specialistId?: Prisma.StringFilter<"ServiceOfferings"> | string
  created_at?: Prisma.DateTimeFilter<"ServiceOfferings"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"ServiceOfferings"> | Date | string
}

export type ServiceOfferingsCreateManySpecialistsInput = {
  id?: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type ServiceOfferingsUpdateWithoutSpecialistsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceOfferingsUncheckedUpdateWithoutSpecialistsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ServiceOfferingsUncheckedUpdateManyWithoutSpecialistsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ServiceOfferingsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  specialistId?: boolean
  created_at?: boolean
  updated_at?: boolean
  specialists?: boolean | Prisma.SpecialistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceOfferings"]>

export type ServiceOfferingsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  specialistId?: boolean
  created_at?: boolean
  updated_at?: boolean
  specialists?: boolean | Prisma.SpecialistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceOfferings"]>

export type ServiceOfferingsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  specialistId?: boolean
  created_at?: boolean
  updated_at?: boolean
  specialists?: boolean | Prisma.SpecialistDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceOfferings"]>

export type ServiceOfferingsSelectScalar = {
  id?: boolean
  specialistId?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type ServiceOfferingsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "specialistId" | "created_at" | "updated_at", ExtArgs["result"]["serviceOfferings"]>
export type ServiceOfferingsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  specialists?: boolean | Prisma.SpecialistDefaultArgs<ExtArgs>
}
export type ServiceOfferingsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  specialists?: boolean | Prisma.SpecialistDefaultArgs<ExtArgs>
}
export type ServiceOfferingsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  specialists?: boolean | Prisma.SpecialistDefaultArgs<ExtArgs>
}

export type $ServiceOfferingsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ServiceOfferings"
  objects: {
    specialists: Prisma.$SpecialistPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    specialistId: string
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["serviceOfferings"]>
  composites: {}
}

export type ServiceOfferingsGetPayload<S extends boolean | null | undefined | ServiceOfferingsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ServiceOfferingsPayload, S>

export type ServiceOfferingsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ServiceOfferingsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServiceOfferingsCountAggregateInputType | true
  }

export interface ServiceOfferingsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ServiceOfferings'], meta: { name: 'ServiceOfferings' } }
  /**
   * Find zero or one ServiceOfferings that matches the filter.
   * @param {ServiceOfferingsFindUniqueArgs} args - Arguments to find a ServiceOfferings
   * @example
   * // Get one ServiceOfferings
   * const serviceOfferings = await prisma.serviceOfferings.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ServiceOfferingsFindUniqueArgs>(args: Prisma.SelectSubset<T, ServiceOfferingsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ServiceOfferingsClient<runtime.Types.Result.GetResult<Prisma.$ServiceOfferingsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ServiceOfferings that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ServiceOfferingsFindUniqueOrThrowArgs} args - Arguments to find a ServiceOfferings
   * @example
   * // Get one ServiceOfferings
   * const serviceOfferings = await prisma.serviceOfferings.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ServiceOfferingsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ServiceOfferingsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceOfferingsClient<runtime.Types.Result.GetResult<Prisma.$ServiceOfferingsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceOfferings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceOfferingsFindFirstArgs} args - Arguments to find a ServiceOfferings
   * @example
   * // Get one ServiceOfferings
   * const serviceOfferings = await prisma.serviceOfferings.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ServiceOfferingsFindFirstArgs>(args?: Prisma.SelectSubset<T, ServiceOfferingsFindFirstArgs<ExtArgs>>): Prisma.Prisma__ServiceOfferingsClient<runtime.Types.Result.GetResult<Prisma.$ServiceOfferingsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceOfferings that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceOfferingsFindFirstOrThrowArgs} args - Arguments to find a ServiceOfferings
   * @example
   * // Get one ServiceOfferings
   * const serviceOfferings = await prisma.serviceOfferings.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ServiceOfferingsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ServiceOfferingsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceOfferingsClient<runtime.Types.Result.GetResult<Prisma.$ServiceOfferingsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ServiceOfferings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceOfferingsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ServiceOfferings
   * const serviceOfferings = await prisma.serviceOfferings.findMany()
   * 
   * // Get first 10 ServiceOfferings
   * const serviceOfferings = await prisma.serviceOfferings.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const serviceOfferingsWithIdOnly = await prisma.serviceOfferings.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ServiceOfferingsFindManyArgs>(args?: Prisma.SelectSubset<T, ServiceOfferingsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceOfferingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ServiceOfferings.
   * @param {ServiceOfferingsCreateArgs} args - Arguments to create a ServiceOfferings.
   * @example
   * // Create one ServiceOfferings
   * const ServiceOfferings = await prisma.serviceOfferings.create({
   *   data: {
   *     // ... data to create a ServiceOfferings
   *   }
   * })
   * 
   */
  create<T extends ServiceOfferingsCreateArgs>(args: Prisma.SelectSubset<T, ServiceOfferingsCreateArgs<ExtArgs>>): Prisma.Prisma__ServiceOfferingsClient<runtime.Types.Result.GetResult<Prisma.$ServiceOfferingsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ServiceOfferings.
   * @param {ServiceOfferingsCreateManyArgs} args - Arguments to create many ServiceOfferings.
   * @example
   * // Create many ServiceOfferings
   * const serviceOfferings = await prisma.serviceOfferings.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ServiceOfferingsCreateManyArgs>(args?: Prisma.SelectSubset<T, ServiceOfferingsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ServiceOfferings and returns the data saved in the database.
   * @param {ServiceOfferingsCreateManyAndReturnArgs} args - Arguments to create many ServiceOfferings.
   * @example
   * // Create many ServiceOfferings
   * const serviceOfferings = await prisma.serviceOfferings.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ServiceOfferings and only return the `id`
   * const serviceOfferingsWithIdOnly = await prisma.serviceOfferings.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ServiceOfferingsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ServiceOfferingsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceOfferingsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ServiceOfferings.
   * @param {ServiceOfferingsDeleteArgs} args - Arguments to delete one ServiceOfferings.
   * @example
   * // Delete one ServiceOfferings
   * const ServiceOfferings = await prisma.serviceOfferings.delete({
   *   where: {
   *     // ... filter to delete one ServiceOfferings
   *   }
   * })
   * 
   */
  delete<T extends ServiceOfferingsDeleteArgs>(args: Prisma.SelectSubset<T, ServiceOfferingsDeleteArgs<ExtArgs>>): Prisma.Prisma__ServiceOfferingsClient<runtime.Types.Result.GetResult<Prisma.$ServiceOfferingsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ServiceOfferings.
   * @param {ServiceOfferingsUpdateArgs} args - Arguments to update one ServiceOfferings.
   * @example
   * // Update one ServiceOfferings
   * const serviceOfferings = await prisma.serviceOfferings.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ServiceOfferingsUpdateArgs>(args: Prisma.SelectSubset<T, ServiceOfferingsUpdateArgs<ExtArgs>>): Prisma.Prisma__ServiceOfferingsClient<runtime.Types.Result.GetResult<Prisma.$ServiceOfferingsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ServiceOfferings.
   * @param {ServiceOfferingsDeleteManyArgs} args - Arguments to filter ServiceOfferings to delete.
   * @example
   * // Delete a few ServiceOfferings
   * const { count } = await prisma.serviceOfferings.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ServiceOfferingsDeleteManyArgs>(args?: Prisma.SelectSubset<T, ServiceOfferingsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceOfferings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceOfferingsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ServiceOfferings
   * const serviceOfferings = await prisma.serviceOfferings.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ServiceOfferingsUpdateManyArgs>(args: Prisma.SelectSubset<T, ServiceOfferingsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceOfferings and returns the data updated in the database.
   * @param {ServiceOfferingsUpdateManyAndReturnArgs} args - Arguments to update many ServiceOfferings.
   * @example
   * // Update many ServiceOfferings
   * const serviceOfferings = await prisma.serviceOfferings.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ServiceOfferings and only return the `id`
   * const serviceOfferingsWithIdOnly = await prisma.serviceOfferings.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ServiceOfferingsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ServiceOfferingsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceOfferingsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ServiceOfferings.
   * @param {ServiceOfferingsUpsertArgs} args - Arguments to update or create a ServiceOfferings.
   * @example
   * // Update or create a ServiceOfferings
   * const serviceOfferings = await prisma.serviceOfferings.upsert({
   *   create: {
   *     // ... data to create a ServiceOfferings
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ServiceOfferings we want to update
   *   }
   * })
   */
  upsert<T extends ServiceOfferingsUpsertArgs>(args: Prisma.SelectSubset<T, ServiceOfferingsUpsertArgs<ExtArgs>>): Prisma.Prisma__ServiceOfferingsClient<runtime.Types.Result.GetResult<Prisma.$ServiceOfferingsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ServiceOfferings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceOfferingsCountArgs} args - Arguments to filter ServiceOfferings to count.
   * @example
   * // Count the number of ServiceOfferings
   * const count = await prisma.serviceOfferings.count({
   *   where: {
   *     // ... the filter for the ServiceOfferings we want to count
   *   }
   * })
  **/
  count<T extends ServiceOfferingsCountArgs>(
    args?: Prisma.Subset<T, ServiceOfferingsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServiceOfferingsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ServiceOfferings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceOfferingsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServiceOfferingsAggregateArgs>(args: Prisma.Subset<T, ServiceOfferingsAggregateArgs>): Prisma.PrismaPromise<GetServiceOfferingsAggregateType<T>>

  /**
   * Group by ServiceOfferings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceOfferingsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ServiceOfferingsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ServiceOfferingsGroupByArgs['orderBy'] }
      : { orderBy?: ServiceOfferingsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ServiceOfferingsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServiceOfferingsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ServiceOfferings model
 */
readonly fields: ServiceOfferingsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ServiceOfferings.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ServiceOfferingsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  specialists<T extends Prisma.SpecialistDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SpecialistDefaultArgs<ExtArgs>>): Prisma.Prisma__SpecialistClient<runtime.Types.Result.GetResult<Prisma.$SpecialistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ServiceOfferings model
 */
export interface ServiceOfferingsFieldRefs {
  readonly id: Prisma.FieldRef<"ServiceOfferings", 'String'>
  readonly specialistId: Prisma.FieldRef<"ServiceOfferings", 'String'>
  readonly created_at: Prisma.FieldRef<"ServiceOfferings", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"ServiceOfferings", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ServiceOfferings findUnique
 */
export type ServiceOfferingsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceOfferings
   */
  select?: Prisma.ServiceOfferingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceOfferings
   */
  omit?: Prisma.ServiceOfferingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceOfferingsInclude<ExtArgs> | null
  /**
   * Filter, which ServiceOfferings to fetch.
   */
  where: Prisma.ServiceOfferingsWhereUniqueInput
}

/**
 * ServiceOfferings findUniqueOrThrow
 */
export type ServiceOfferingsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceOfferings
   */
  select?: Prisma.ServiceOfferingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceOfferings
   */
  omit?: Prisma.ServiceOfferingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceOfferingsInclude<ExtArgs> | null
  /**
   * Filter, which ServiceOfferings to fetch.
   */
  where: Prisma.ServiceOfferingsWhereUniqueInput
}

/**
 * ServiceOfferings findFirst
 */
export type ServiceOfferingsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceOfferings
   */
  select?: Prisma.ServiceOfferingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceOfferings
   */
  omit?: Prisma.ServiceOfferingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceOfferingsInclude<ExtArgs> | null
  /**
   * Filter, which ServiceOfferings to fetch.
   */
  where?: Prisma.ServiceOfferingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceOfferings to fetch.
   */
  orderBy?: Prisma.ServiceOfferingsOrderByWithRelationInput | Prisma.ServiceOfferingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceOfferings.
   */
  cursor?: Prisma.ServiceOfferingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceOfferings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceOfferings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceOfferings.
   */
  distinct?: Prisma.ServiceOfferingsScalarFieldEnum | Prisma.ServiceOfferingsScalarFieldEnum[]
}

/**
 * ServiceOfferings findFirstOrThrow
 */
export type ServiceOfferingsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceOfferings
   */
  select?: Prisma.ServiceOfferingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceOfferings
   */
  omit?: Prisma.ServiceOfferingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceOfferingsInclude<ExtArgs> | null
  /**
   * Filter, which ServiceOfferings to fetch.
   */
  where?: Prisma.ServiceOfferingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceOfferings to fetch.
   */
  orderBy?: Prisma.ServiceOfferingsOrderByWithRelationInput | Prisma.ServiceOfferingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceOfferings.
   */
  cursor?: Prisma.ServiceOfferingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceOfferings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceOfferings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceOfferings.
   */
  distinct?: Prisma.ServiceOfferingsScalarFieldEnum | Prisma.ServiceOfferingsScalarFieldEnum[]
}

/**
 * ServiceOfferings findMany
 */
export type ServiceOfferingsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceOfferings
   */
  select?: Prisma.ServiceOfferingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceOfferings
   */
  omit?: Prisma.ServiceOfferingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceOfferingsInclude<ExtArgs> | null
  /**
   * Filter, which ServiceOfferings to fetch.
   */
  where?: Prisma.ServiceOfferingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceOfferings to fetch.
   */
  orderBy?: Prisma.ServiceOfferingsOrderByWithRelationInput | Prisma.ServiceOfferingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ServiceOfferings.
   */
  cursor?: Prisma.ServiceOfferingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceOfferings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceOfferings.
   */
  skip?: number
  distinct?: Prisma.ServiceOfferingsScalarFieldEnum | Prisma.ServiceOfferingsScalarFieldEnum[]
}

/**
 * ServiceOfferings create
 */
export type ServiceOfferingsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceOfferings
   */
  select?: Prisma.ServiceOfferingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceOfferings
   */
  omit?: Prisma.ServiceOfferingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceOfferingsInclude<ExtArgs> | null
  /**
   * The data needed to create a ServiceOfferings.
   */
  data: Prisma.XOR<Prisma.ServiceOfferingsCreateInput, Prisma.ServiceOfferingsUncheckedCreateInput>
}

/**
 * ServiceOfferings createMany
 */
export type ServiceOfferingsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ServiceOfferings.
   */
  data: Prisma.ServiceOfferingsCreateManyInput | Prisma.ServiceOfferingsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ServiceOfferings createManyAndReturn
 */
export type ServiceOfferingsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceOfferings
   */
  select?: Prisma.ServiceOfferingsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceOfferings
   */
  omit?: Prisma.ServiceOfferingsOmit<ExtArgs> | null
  /**
   * The data used to create many ServiceOfferings.
   */
  data: Prisma.ServiceOfferingsCreateManyInput | Prisma.ServiceOfferingsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceOfferingsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceOfferings update
 */
export type ServiceOfferingsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceOfferings
   */
  select?: Prisma.ServiceOfferingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceOfferings
   */
  omit?: Prisma.ServiceOfferingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceOfferingsInclude<ExtArgs> | null
  /**
   * The data needed to update a ServiceOfferings.
   */
  data: Prisma.XOR<Prisma.ServiceOfferingsUpdateInput, Prisma.ServiceOfferingsUncheckedUpdateInput>
  /**
   * Choose, which ServiceOfferings to update.
   */
  where: Prisma.ServiceOfferingsWhereUniqueInput
}

/**
 * ServiceOfferings updateMany
 */
export type ServiceOfferingsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ServiceOfferings.
   */
  data: Prisma.XOR<Prisma.ServiceOfferingsUpdateManyMutationInput, Prisma.ServiceOfferingsUncheckedUpdateManyInput>
  /**
   * Filter which ServiceOfferings to update
   */
  where?: Prisma.ServiceOfferingsWhereInput
  /**
   * Limit how many ServiceOfferings to update.
   */
  limit?: number
}

/**
 * ServiceOfferings updateManyAndReturn
 */
export type ServiceOfferingsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceOfferings
   */
  select?: Prisma.ServiceOfferingsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceOfferings
   */
  omit?: Prisma.ServiceOfferingsOmit<ExtArgs> | null
  /**
   * The data used to update ServiceOfferings.
   */
  data: Prisma.XOR<Prisma.ServiceOfferingsUpdateManyMutationInput, Prisma.ServiceOfferingsUncheckedUpdateManyInput>
  /**
   * Filter which ServiceOfferings to update
   */
  where?: Prisma.ServiceOfferingsWhereInput
  /**
   * Limit how many ServiceOfferings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceOfferingsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceOfferings upsert
 */
export type ServiceOfferingsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceOfferings
   */
  select?: Prisma.ServiceOfferingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceOfferings
   */
  omit?: Prisma.ServiceOfferingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceOfferingsInclude<ExtArgs> | null
  /**
   * The filter to search for the ServiceOfferings to update in case it exists.
   */
  where: Prisma.ServiceOfferingsWhereUniqueInput
  /**
   * In case the ServiceOfferings found by the `where` argument doesn't exist, create a new ServiceOfferings with this data.
   */
  create: Prisma.XOR<Prisma.ServiceOfferingsCreateInput, Prisma.ServiceOfferingsUncheckedCreateInput>
  /**
   * In case the ServiceOfferings was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ServiceOfferingsUpdateInput, Prisma.ServiceOfferingsUncheckedUpdateInput>
}

/**
 * ServiceOfferings delete
 */
export type ServiceOfferingsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceOfferings
   */
  select?: Prisma.ServiceOfferingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceOfferings
   */
  omit?: Prisma.ServiceOfferingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceOfferingsInclude<ExtArgs> | null
  /**
   * Filter which ServiceOfferings to delete.
   */
  where: Prisma.ServiceOfferingsWhereUniqueInput
}

/**
 * ServiceOfferings deleteMany
 */
export type ServiceOfferingsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceOfferings to delete
   */
  where?: Prisma.ServiceOfferingsWhereInput
  /**
   * Limit how many ServiceOfferings to delete.
   */
  limit?: number
}

/**
 * ServiceOfferings without action
 */
export type ServiceOfferingsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceOfferings
   */
  select?: Prisma.ServiceOfferingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceOfferings
   */
  omit?: Prisma.ServiceOfferingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceOfferingsInclude<ExtArgs> | null
}
