
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Specialist` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Specialist
 * 
 */
export type SpecialistModel = runtime.Types.Result.DefaultSelection<Prisma.$SpecialistPayload>

export type AggregateSpecialist = {
  _count: SpecialistCountAggregateOutputType | null
  _avg: SpecialistAvgAggregateOutputType | null
  _sum: SpecialistSumAggregateOutputType | null
  _min: SpecialistMinAggregateOutputType | null
  _max: SpecialistMaxAggregateOutputType | null
}

export type SpecialistAvgAggregateOutputType = {
  average_rating: runtime.Decimal | null
  total_number_of_ratings: number | null
  base_price: runtime.Decimal | null
  platform_fee: runtime.Decimal | null
  final_price: runtime.Decimal | null
  duration_days: number | null
}

export type SpecialistSumAggregateOutputType = {
  average_rating: runtime.Decimal | null
  total_number_of_ratings: number | null
  base_price: runtime.Decimal | null
  platform_fee: runtime.Decimal | null
  final_price: runtime.Decimal | null
  duration_days: number | null
}

export type SpecialistMinAggregateOutputType = {
  id: string | null
  average_rating: runtime.Decimal | null
  is_draft: boolean | null
  total_number_of_ratings: number | null
  title: string | null
  slug: string | null
  description: string | null
  base_price: runtime.Decimal | null
  platform_fee: runtime.Decimal | null
  final_price: runtime.Decimal | null
  verification_status: $Enums.VerificationStatus | null
  is_verified: boolean | null
  duration_days: number | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
}

export type SpecialistMaxAggregateOutputType = {
  id: string | null
  average_rating: runtime.Decimal | null
  is_draft: boolean | null
  total_number_of_ratings: number | null
  title: string | null
  slug: string | null
  description: string | null
  base_price: runtime.Decimal | null
  platform_fee: runtime.Decimal | null
  final_price: runtime.Decimal | null
  verification_status: $Enums.VerificationStatus | null
  is_verified: boolean | null
  duration_days: number | null
  created_at: Date | null
  updated_at: Date | null
  deleted_at: Date | null
}

export type SpecialistCountAggregateOutputType = {
  id: number
  average_rating: number
  is_draft: number
  total_number_of_ratings: number
  title: number
  slug: number
  description: number
  base_price: number
  platform_fee: number
  final_price: number
  verification_status: number
  is_verified: number
  duration_days: number
  created_at: number
  updated_at: number
  deleted_at: number
  _all: number
}


export type SpecialistAvgAggregateInputType = {
  average_rating?: true
  total_number_of_ratings?: true
  base_price?: true
  platform_fee?: true
  final_price?: true
  duration_days?: true
}

export type SpecialistSumAggregateInputType = {
  average_rating?: true
  total_number_of_ratings?: true
  base_price?: true
  platform_fee?: true
  final_price?: true
  duration_days?: true
}

export type SpecialistMinAggregateInputType = {
  id?: true
  average_rating?: true
  is_draft?: true
  total_number_of_ratings?: true
  title?: true
  slug?: true
  description?: true
  base_price?: true
  platform_fee?: true
  final_price?: true
  verification_status?: true
  is_verified?: true
  duration_days?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
}

export type SpecialistMaxAggregateInputType = {
  id?: true
  average_rating?: true
  is_draft?: true
  total_number_of_ratings?: true
  title?: true
  slug?: true
  description?: true
  base_price?: true
  platform_fee?: true
  final_price?: true
  verification_status?: true
  is_verified?: true
  duration_days?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
}

export type SpecialistCountAggregateInputType = {
  id?: true
  average_rating?: true
  is_draft?: true
  total_number_of_ratings?: true
  title?: true
  slug?: true
  description?: true
  base_price?: true
  platform_fee?: true
  final_price?: true
  verification_status?: true
  is_verified?: true
  duration_days?: true
  created_at?: true
  updated_at?: true
  deleted_at?: true
  _all?: true
}

export type SpecialistAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Specialist to aggregate.
   */
  where?: Prisma.SpecialistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Specialists to fetch.
   */
  orderBy?: Prisma.SpecialistOrderByWithRelationInput | Prisma.SpecialistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SpecialistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Specialists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Specialists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Specialists
  **/
  _count?: true | SpecialistCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SpecialistAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SpecialistSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SpecialistMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SpecialistMaxAggregateInputType
}

export type GetSpecialistAggregateType<T extends SpecialistAggregateArgs> = {
      [P in keyof T & keyof AggregateSpecialist]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSpecialist[P]>
    : Prisma.GetScalarType<T[P], AggregateSpecialist[P]>
}




export type SpecialistGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SpecialistWhereInput
  orderBy?: Prisma.SpecialistOrderByWithAggregationInput | Prisma.SpecialistOrderByWithAggregationInput[]
  by: Prisma.SpecialistScalarFieldEnum[] | Prisma.SpecialistScalarFieldEnum
  having?: Prisma.SpecialistScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SpecialistCountAggregateInputType | true
  _avg?: SpecialistAvgAggregateInputType
  _sum?: SpecialistSumAggregateInputType
  _min?: SpecialistMinAggregateInputType
  _max?: SpecialistMaxAggregateInputType
}

export type SpecialistGroupByOutputType = {
  id: string
  average_rating: runtime.Decimal
  is_draft: boolean
  total_number_of_ratings: number
  title: string
  slug: string
  description: string | null
  base_price: runtime.Decimal
  platform_fee: runtime.Decimal
  final_price: runtime.Decimal
  verification_status: $Enums.VerificationStatus
  is_verified: boolean
  duration_days: number | null
  created_at: Date
  updated_at: Date
  deleted_at: Date | null
  _count: SpecialistCountAggregateOutputType | null
  _avg: SpecialistAvgAggregateOutputType | null
  _sum: SpecialistSumAggregateOutputType | null
  _min: SpecialistMinAggregateOutputType | null
  _max: SpecialistMaxAggregateOutputType | null
}

type GetSpecialistGroupByPayload<T extends SpecialistGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SpecialistGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SpecialistGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SpecialistGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SpecialistGroupByOutputType[P]>
      }
    >
  >



export type SpecialistWhereInput = {
  AND?: Prisma.SpecialistWhereInput | Prisma.SpecialistWhereInput[]
  OR?: Prisma.SpecialistWhereInput[]
  NOT?: Prisma.SpecialistWhereInput | Prisma.SpecialistWhereInput[]
  id?: Prisma.StringFilter<"Specialist"> | string
  average_rating?: Prisma.DecimalFilter<"Specialist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: Prisma.BoolFilter<"Specialist"> | boolean
  total_number_of_ratings?: Prisma.IntFilter<"Specialist"> | number
  title?: Prisma.StringFilter<"Specialist"> | string
  slug?: Prisma.StringFilter<"Specialist"> | string
  description?: Prisma.StringNullableFilter<"Specialist"> | string | null
  base_price?: Prisma.DecimalFilter<"Specialist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee?: Prisma.DecimalFilter<"Specialist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price?: Prisma.DecimalFilter<"Specialist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: Prisma.EnumVerificationStatusFilter<"Specialist"> | $Enums.VerificationStatus
  is_verified?: Prisma.BoolFilter<"Specialist"> | boolean
  duration_days?: Prisma.IntNullableFilter<"Specialist"> | number | null
  created_at?: Prisma.DateTimeFilter<"Specialist"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Specialist"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"Specialist"> | Date | string | null
  media?: Prisma.MediaListRelationFilter
  service_offerings?: Prisma.ServiceOfferingsListRelationFilter
}

export type SpecialistOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  average_rating?: Prisma.SortOrder
  is_draft?: Prisma.SortOrder
  total_number_of_ratings?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  base_price?: Prisma.SortOrder
  platform_fee?: Prisma.SortOrder
  final_price?: Prisma.SortOrder
  verification_status?: Prisma.SortOrder
  is_verified?: Prisma.SortOrder
  duration_days?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  media?: Prisma.MediaOrderByRelationAggregateInput
  service_offerings?: Prisma.ServiceOfferingsOrderByRelationAggregateInput
}

export type SpecialistWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.SpecialistWhereInput | Prisma.SpecialistWhereInput[]
  OR?: Prisma.SpecialistWhereInput[]
  NOT?: Prisma.SpecialistWhereInput | Prisma.SpecialistWhereInput[]
  average_rating?: Prisma.DecimalFilter<"Specialist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: Prisma.BoolFilter<"Specialist"> | boolean
  total_number_of_ratings?: Prisma.IntFilter<"Specialist"> | number
  title?: Prisma.StringFilter<"Specialist"> | string
  description?: Prisma.StringNullableFilter<"Specialist"> | string | null
  base_price?: Prisma.DecimalFilter<"Specialist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee?: Prisma.DecimalFilter<"Specialist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price?: Prisma.DecimalFilter<"Specialist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: Prisma.EnumVerificationStatusFilter<"Specialist"> | $Enums.VerificationStatus
  is_verified?: Prisma.BoolFilter<"Specialist"> | boolean
  duration_days?: Prisma.IntNullableFilter<"Specialist"> | number | null
  created_at?: Prisma.DateTimeFilter<"Specialist"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Specialist"> | Date | string
  deleted_at?: Prisma.DateTimeNullableFilter<"Specialist"> | Date | string | null
  media?: Prisma.MediaListRelationFilter
  service_offerings?: Prisma.ServiceOfferingsListRelationFilter
}, "id" | "slug">

export type SpecialistOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  average_rating?: Prisma.SortOrder
  is_draft?: Prisma.SortOrder
  total_number_of_ratings?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  base_price?: Prisma.SortOrder
  platform_fee?: Prisma.SortOrder
  final_price?: Prisma.SortOrder
  verification_status?: Prisma.SortOrder
  is_verified?: Prisma.SortOrder
  duration_days?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.SpecialistCountOrderByAggregateInput
  _avg?: Prisma.SpecialistAvgOrderByAggregateInput
  _max?: Prisma.SpecialistMaxOrderByAggregateInput
  _min?: Prisma.SpecialistMinOrderByAggregateInput
  _sum?: Prisma.SpecialistSumOrderByAggregateInput
}

export type SpecialistScalarWhereWithAggregatesInput = {
  AND?: Prisma.SpecialistScalarWhereWithAggregatesInput | Prisma.SpecialistScalarWhereWithAggregatesInput[]
  OR?: Prisma.SpecialistScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SpecialistScalarWhereWithAggregatesInput | Prisma.SpecialistScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Specialist"> | string
  average_rating?: Prisma.DecimalWithAggregatesFilter<"Specialist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: Prisma.BoolWithAggregatesFilter<"Specialist"> | boolean
  total_number_of_ratings?: Prisma.IntWithAggregatesFilter<"Specialist"> | number
  title?: Prisma.StringWithAggregatesFilter<"Specialist"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Specialist"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Specialist"> | string | null
  base_price?: Prisma.DecimalWithAggregatesFilter<"Specialist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee?: Prisma.DecimalWithAggregatesFilter<"Specialist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price?: Prisma.DecimalWithAggregatesFilter<"Specialist"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: Prisma.EnumVerificationStatusWithAggregatesFilter<"Specialist"> | $Enums.VerificationStatus
  is_verified?: Prisma.BoolWithAggregatesFilter<"Specialist"> | boolean
  duration_days?: Prisma.IntNullableWithAggregatesFilter<"Specialist"> | number | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Specialist"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Specialist"> | Date | string
  deleted_at?: Prisma.DateTimeNullableWithAggregatesFilter<"Specialist"> | Date | string | null
}

export type SpecialistCreateInput = {
  id?: string
  average_rating?: runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: boolean
  total_number_of_ratings?: number
  title: string
  slug: string
  description?: string | null
  base_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: $Enums.VerificationStatus
  is_verified?: boolean
  duration_days?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  media?: Prisma.MediaCreateNestedManyWithoutSpecialistsInput
  service_offerings?: Prisma.ServiceOfferingsCreateNestedManyWithoutSpecialistsInput
}

export type SpecialistUncheckedCreateInput = {
  id?: string
  average_rating?: runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: boolean
  total_number_of_ratings?: number
  title: string
  slug: string
  description?: string | null
  base_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: $Enums.VerificationStatus
  is_verified?: boolean
  duration_days?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  media?: Prisma.MediaUncheckedCreateNestedManyWithoutSpecialistsInput
  service_offerings?: Prisma.ServiceOfferingsUncheckedCreateNestedManyWithoutSpecialistsInput
}

export type SpecialistUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  average_rating?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  total_number_of_ratings?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  base_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  duration_days?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  media?: Prisma.MediaUpdateManyWithoutSpecialistsNestedInput
  service_offerings?: Prisma.ServiceOfferingsUpdateManyWithoutSpecialistsNestedInput
}

export type SpecialistUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  average_rating?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  total_number_of_ratings?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  base_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  duration_days?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  media?: Prisma.MediaUncheckedUpdateManyWithoutSpecialistsNestedInput
  service_offerings?: Prisma.ServiceOfferingsUncheckedUpdateManyWithoutSpecialistsNestedInput
}

export type SpecialistCreateManyInput = {
  id?: string
  average_rating?: runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: boolean
  total_number_of_ratings?: number
  title: string
  slug: string
  description?: string | null
  base_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: $Enums.VerificationStatus
  is_verified?: boolean
  duration_days?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
}

export type SpecialistUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  average_rating?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  total_number_of_ratings?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  base_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  duration_days?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SpecialistUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  average_rating?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  total_number_of_ratings?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  base_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  duration_days?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type SpecialistScalarRelationFilter = {
  is?: Prisma.SpecialistWhereInput
  isNot?: Prisma.SpecialistWhereInput
}

export type SpecialistCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  average_rating?: Prisma.SortOrder
  is_draft?: Prisma.SortOrder
  total_number_of_ratings?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  base_price?: Prisma.SortOrder
  platform_fee?: Prisma.SortOrder
  final_price?: Prisma.SortOrder
  verification_status?: Prisma.SortOrder
  is_verified?: Prisma.SortOrder
  duration_days?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type SpecialistAvgOrderByAggregateInput = {
  average_rating?: Prisma.SortOrder
  total_number_of_ratings?: Prisma.SortOrder
  base_price?: Prisma.SortOrder
  platform_fee?: Prisma.SortOrder
  final_price?: Prisma.SortOrder
  duration_days?: Prisma.SortOrder
}

export type SpecialistMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  average_rating?: Prisma.SortOrder
  is_draft?: Prisma.SortOrder
  total_number_of_ratings?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  base_price?: Prisma.SortOrder
  platform_fee?: Prisma.SortOrder
  final_price?: Prisma.SortOrder
  verification_status?: Prisma.SortOrder
  is_verified?: Prisma.SortOrder
  duration_days?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type SpecialistMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  average_rating?: Prisma.SortOrder
  is_draft?: Prisma.SortOrder
  total_number_of_ratings?: Prisma.SortOrder
  title?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  base_price?: Prisma.SortOrder
  platform_fee?: Prisma.SortOrder
  final_price?: Prisma.SortOrder
  verification_status?: Prisma.SortOrder
  is_verified?: Prisma.SortOrder
  duration_days?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  deleted_at?: Prisma.SortOrder
}

export type SpecialistSumOrderByAggregateInput = {
  average_rating?: Prisma.SortOrder
  total_number_of_ratings?: Prisma.SortOrder
  base_price?: Prisma.SortOrder
  platform_fee?: Prisma.SortOrder
  final_price?: Prisma.SortOrder
  duration_days?: Prisma.SortOrder
}

export type SpecialistCreateNestedOneWithoutMediaInput = {
  create?: Prisma.XOR<Prisma.SpecialistCreateWithoutMediaInput, Prisma.SpecialistUncheckedCreateWithoutMediaInput>
  connectOrCreate?: Prisma.SpecialistCreateOrConnectWithoutMediaInput
  connect?: Prisma.SpecialistWhereUniqueInput
}

export type SpecialistUpdateOneRequiredWithoutMediaNestedInput = {
  create?: Prisma.XOR<Prisma.SpecialistCreateWithoutMediaInput, Prisma.SpecialistUncheckedCreateWithoutMediaInput>
  connectOrCreate?: Prisma.SpecialistCreateOrConnectWithoutMediaInput
  upsert?: Prisma.SpecialistUpsertWithoutMediaInput
  connect?: Prisma.SpecialistWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SpecialistUpdateToOneWithWhereWithoutMediaInput, Prisma.SpecialistUpdateWithoutMediaInput>, Prisma.SpecialistUncheckedUpdateWithoutMediaInput>
}

export type SpecialistCreateNestedOneWithoutService_offeringsInput = {
  create?: Prisma.XOR<Prisma.SpecialistCreateWithoutService_offeringsInput, Prisma.SpecialistUncheckedCreateWithoutService_offeringsInput>
  connectOrCreate?: Prisma.SpecialistCreateOrConnectWithoutService_offeringsInput
  connect?: Prisma.SpecialistWhereUniqueInput
}

export type SpecialistUpdateOneRequiredWithoutService_offeringsNestedInput = {
  create?: Prisma.XOR<Prisma.SpecialistCreateWithoutService_offeringsInput, Prisma.SpecialistUncheckedCreateWithoutService_offeringsInput>
  connectOrCreate?: Prisma.SpecialistCreateOrConnectWithoutService_offeringsInput
  upsert?: Prisma.SpecialistUpsertWithoutService_offeringsInput
  connect?: Prisma.SpecialistWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SpecialistUpdateToOneWithWhereWithoutService_offeringsInput, Prisma.SpecialistUpdateWithoutService_offeringsInput>, Prisma.SpecialistUncheckedUpdateWithoutService_offeringsInput>
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type EnumVerificationStatusFieldUpdateOperationsInput = {
  set?: $Enums.VerificationStatus
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type SpecialistCreateWithoutMediaInput = {
  id?: string
  average_rating?: runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: boolean
  total_number_of_ratings?: number
  title: string
  slug: string
  description?: string | null
  base_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: $Enums.VerificationStatus
  is_verified?: boolean
  duration_days?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  service_offerings?: Prisma.ServiceOfferingsCreateNestedManyWithoutSpecialistsInput
}

export type SpecialistUncheckedCreateWithoutMediaInput = {
  id?: string
  average_rating?: runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: boolean
  total_number_of_ratings?: number
  title: string
  slug: string
  description?: string | null
  base_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: $Enums.VerificationStatus
  is_verified?: boolean
  duration_days?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  service_offerings?: Prisma.ServiceOfferingsUncheckedCreateNestedManyWithoutSpecialistsInput
}

export type SpecialistCreateOrConnectWithoutMediaInput = {
  where: Prisma.SpecialistWhereUniqueInput
  create: Prisma.XOR<Prisma.SpecialistCreateWithoutMediaInput, Prisma.SpecialistUncheckedCreateWithoutMediaInput>
}

export type SpecialistUpsertWithoutMediaInput = {
  update: Prisma.XOR<Prisma.SpecialistUpdateWithoutMediaInput, Prisma.SpecialistUncheckedUpdateWithoutMediaInput>
  create: Prisma.XOR<Prisma.SpecialistCreateWithoutMediaInput, Prisma.SpecialistUncheckedCreateWithoutMediaInput>
  where?: Prisma.SpecialistWhereInput
}

export type SpecialistUpdateToOneWithWhereWithoutMediaInput = {
  where?: Prisma.SpecialistWhereInput
  data: Prisma.XOR<Prisma.SpecialistUpdateWithoutMediaInput, Prisma.SpecialistUncheckedUpdateWithoutMediaInput>
}

export type SpecialistUpdateWithoutMediaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  average_rating?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  total_number_of_ratings?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  base_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  duration_days?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  service_offerings?: Prisma.ServiceOfferingsUpdateManyWithoutSpecialistsNestedInput
}

export type SpecialistUncheckedUpdateWithoutMediaInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  average_rating?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  total_number_of_ratings?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  base_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  duration_days?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  service_offerings?: Prisma.ServiceOfferingsUncheckedUpdateManyWithoutSpecialistsNestedInput
}

export type SpecialistCreateWithoutService_offeringsInput = {
  id?: string
  average_rating?: runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: boolean
  total_number_of_ratings?: number
  title: string
  slug: string
  description?: string | null
  base_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: $Enums.VerificationStatus
  is_verified?: boolean
  duration_days?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  media?: Prisma.MediaCreateNestedManyWithoutSpecialistsInput
}

export type SpecialistUncheckedCreateWithoutService_offeringsInput = {
  id?: string
  average_rating?: runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: boolean
  total_number_of_ratings?: number
  title: string
  slug: string
  description?: string | null
  base_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee: runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price: runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: $Enums.VerificationStatus
  is_verified?: boolean
  duration_days?: number | null
  created_at?: Date | string
  updated_at?: Date | string
  deleted_at?: Date | string | null
  media?: Prisma.MediaUncheckedCreateNestedManyWithoutSpecialistsInput
}

export type SpecialistCreateOrConnectWithoutService_offeringsInput = {
  where: Prisma.SpecialistWhereUniqueInput
  create: Prisma.XOR<Prisma.SpecialistCreateWithoutService_offeringsInput, Prisma.SpecialistUncheckedCreateWithoutService_offeringsInput>
}

export type SpecialistUpsertWithoutService_offeringsInput = {
  update: Prisma.XOR<Prisma.SpecialistUpdateWithoutService_offeringsInput, Prisma.SpecialistUncheckedUpdateWithoutService_offeringsInput>
  create: Prisma.XOR<Prisma.SpecialistCreateWithoutService_offeringsInput, Prisma.SpecialistUncheckedCreateWithoutService_offeringsInput>
  where?: Prisma.SpecialistWhereInput
}

export type SpecialistUpdateToOneWithWhereWithoutService_offeringsInput = {
  where?: Prisma.SpecialistWhereInput
  data: Prisma.XOR<Prisma.SpecialistUpdateWithoutService_offeringsInput, Prisma.SpecialistUncheckedUpdateWithoutService_offeringsInput>
}

export type SpecialistUpdateWithoutService_offeringsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  average_rating?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  total_number_of_ratings?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  base_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  duration_days?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  media?: Prisma.MediaUpdateManyWithoutSpecialistsNestedInput
}

export type SpecialistUncheckedUpdateWithoutService_offeringsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  average_rating?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  is_draft?: Prisma.BoolFieldUpdateOperationsInput | boolean
  total_number_of_ratings?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  base_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  platform_fee?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  final_price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  verification_status?: Prisma.EnumVerificationStatusFieldUpdateOperationsInput | $Enums.VerificationStatus
  is_verified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  duration_days?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deleted_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  media?: Prisma.MediaUncheckedUpdateManyWithoutSpecialistsNestedInput
}


/**
 * Count Type SpecialistCountOutputType
 */

export type SpecialistCountOutputType = {
  media: number
  service_offerings: number
}

export type SpecialistCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  media?: boolean | SpecialistCountOutputTypeCountMediaArgs
  service_offerings?: boolean | SpecialistCountOutputTypeCountService_offeringsArgs
}

/**
 * SpecialistCountOutputType without action
 */
export type SpecialistCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SpecialistCountOutputType
   */
  select?: Prisma.SpecialistCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SpecialistCountOutputType without action
 */
export type SpecialistCountOutputTypeCountMediaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MediaWhereInput
}

/**
 * SpecialistCountOutputType without action
 */
export type SpecialistCountOutputTypeCountService_offeringsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceOfferingsWhereInput
}


export type SpecialistSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  average_rating?: boolean
  is_draft?: boolean
  total_number_of_ratings?: boolean
  title?: boolean
  slug?: boolean
  description?: boolean
  base_price?: boolean
  platform_fee?: boolean
  final_price?: boolean
  verification_status?: boolean
  is_verified?: boolean
  duration_days?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
  media?: boolean | Prisma.Specialist$mediaArgs<ExtArgs>
  service_offerings?: boolean | Prisma.Specialist$service_offeringsArgs<ExtArgs>
  _count?: boolean | Prisma.SpecialistCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["specialist"]>

export type SpecialistSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  average_rating?: boolean
  is_draft?: boolean
  total_number_of_ratings?: boolean
  title?: boolean
  slug?: boolean
  description?: boolean
  base_price?: boolean
  platform_fee?: boolean
  final_price?: boolean
  verification_status?: boolean
  is_verified?: boolean
  duration_days?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
}, ExtArgs["result"]["specialist"]>

export type SpecialistSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  average_rating?: boolean
  is_draft?: boolean
  total_number_of_ratings?: boolean
  title?: boolean
  slug?: boolean
  description?: boolean
  base_price?: boolean
  platform_fee?: boolean
  final_price?: boolean
  verification_status?: boolean
  is_verified?: boolean
  duration_days?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
}, ExtArgs["result"]["specialist"]>

export type SpecialistSelectScalar = {
  id?: boolean
  average_rating?: boolean
  is_draft?: boolean
  total_number_of_ratings?: boolean
  title?: boolean
  slug?: boolean
  description?: boolean
  base_price?: boolean
  platform_fee?: boolean
  final_price?: boolean
  verification_status?: boolean
  is_verified?: boolean
  duration_days?: boolean
  created_at?: boolean
  updated_at?: boolean
  deleted_at?: boolean
}

export type SpecialistOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "average_rating" | "is_draft" | "total_number_of_ratings" | "title" | "slug" | "description" | "base_price" | "platform_fee" | "final_price" | "verification_status" | "is_verified" | "duration_days" | "created_at" | "updated_at" | "deleted_at", ExtArgs["result"]["specialist"]>
export type SpecialistInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  media?: boolean | Prisma.Specialist$mediaArgs<ExtArgs>
  service_offerings?: boolean | Prisma.Specialist$service_offeringsArgs<ExtArgs>
  _count?: boolean | Prisma.SpecialistCountOutputTypeDefaultArgs<ExtArgs>
}
export type SpecialistIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SpecialistIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SpecialistPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Specialist"
  objects: {
    media: Prisma.$MediaPayload<ExtArgs>[]
    service_offerings: Prisma.$ServiceOfferingsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    average_rating: runtime.Decimal
    is_draft: boolean
    total_number_of_ratings: number
    title: string
    slug: string
    description: string | null
    base_price: runtime.Decimal
    platform_fee: runtime.Decimal
    final_price: runtime.Decimal
    verification_status: $Enums.VerificationStatus
    is_verified: boolean
    duration_days: number | null
    created_at: Date
    updated_at: Date
    deleted_at: Date | null
  }, ExtArgs["result"]["specialist"]>
  composites: {}
}

export type SpecialistGetPayload<S extends boolean | null | undefined | SpecialistDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SpecialistPayload, S>

export type SpecialistCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SpecialistFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SpecialistCountAggregateInputType | true
  }

export interface SpecialistDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Specialist'], meta: { name: 'Specialist' } }
  /**
   * Find zero or one Specialist that matches the filter.
   * @param {SpecialistFindUniqueArgs} args - Arguments to find a Specialist
   * @example
   * // Get one Specialist
   * const specialist = await prisma.specialist.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SpecialistFindUniqueArgs>(args: Prisma.SelectSubset<T, SpecialistFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SpecialistClient<runtime.Types.Result.GetResult<Prisma.$SpecialistPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Specialist that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SpecialistFindUniqueOrThrowArgs} args - Arguments to find a Specialist
   * @example
   * // Get one Specialist
   * const specialist = await prisma.specialist.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SpecialistFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SpecialistFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SpecialistClient<runtime.Types.Result.GetResult<Prisma.$SpecialistPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Specialist that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpecialistFindFirstArgs} args - Arguments to find a Specialist
   * @example
   * // Get one Specialist
   * const specialist = await prisma.specialist.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SpecialistFindFirstArgs>(args?: Prisma.SelectSubset<T, SpecialistFindFirstArgs<ExtArgs>>): Prisma.Prisma__SpecialistClient<runtime.Types.Result.GetResult<Prisma.$SpecialistPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Specialist that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpecialistFindFirstOrThrowArgs} args - Arguments to find a Specialist
   * @example
   * // Get one Specialist
   * const specialist = await prisma.specialist.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SpecialistFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SpecialistFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SpecialistClient<runtime.Types.Result.GetResult<Prisma.$SpecialistPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Specialists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpecialistFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Specialists
   * const specialists = await prisma.specialist.findMany()
   * 
   * // Get first 10 Specialists
   * const specialists = await prisma.specialist.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const specialistWithIdOnly = await prisma.specialist.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SpecialistFindManyArgs>(args?: Prisma.SelectSubset<T, SpecialistFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpecialistPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Specialist.
   * @param {SpecialistCreateArgs} args - Arguments to create a Specialist.
   * @example
   * // Create one Specialist
   * const Specialist = await prisma.specialist.create({
   *   data: {
   *     // ... data to create a Specialist
   *   }
   * })
   * 
   */
  create<T extends SpecialistCreateArgs>(args: Prisma.SelectSubset<T, SpecialistCreateArgs<ExtArgs>>): Prisma.Prisma__SpecialistClient<runtime.Types.Result.GetResult<Prisma.$SpecialistPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Specialists.
   * @param {SpecialistCreateManyArgs} args - Arguments to create many Specialists.
   * @example
   * // Create many Specialists
   * const specialist = await prisma.specialist.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SpecialistCreateManyArgs>(args?: Prisma.SelectSubset<T, SpecialistCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Specialists and returns the data saved in the database.
   * @param {SpecialistCreateManyAndReturnArgs} args - Arguments to create many Specialists.
   * @example
   * // Create many Specialists
   * const specialist = await prisma.specialist.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Specialists and only return the `id`
   * const specialistWithIdOnly = await prisma.specialist.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SpecialistCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SpecialistCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpecialistPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Specialist.
   * @param {SpecialistDeleteArgs} args - Arguments to delete one Specialist.
   * @example
   * // Delete one Specialist
   * const Specialist = await prisma.specialist.delete({
   *   where: {
   *     // ... filter to delete one Specialist
   *   }
   * })
   * 
   */
  delete<T extends SpecialistDeleteArgs>(args: Prisma.SelectSubset<T, SpecialistDeleteArgs<ExtArgs>>): Prisma.Prisma__SpecialistClient<runtime.Types.Result.GetResult<Prisma.$SpecialistPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Specialist.
   * @param {SpecialistUpdateArgs} args - Arguments to update one Specialist.
   * @example
   * // Update one Specialist
   * const specialist = await prisma.specialist.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SpecialistUpdateArgs>(args: Prisma.SelectSubset<T, SpecialistUpdateArgs<ExtArgs>>): Prisma.Prisma__SpecialistClient<runtime.Types.Result.GetResult<Prisma.$SpecialistPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Specialists.
   * @param {SpecialistDeleteManyArgs} args - Arguments to filter Specialists to delete.
   * @example
   * // Delete a few Specialists
   * const { count } = await prisma.specialist.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SpecialistDeleteManyArgs>(args?: Prisma.SelectSubset<T, SpecialistDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Specialists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpecialistUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Specialists
   * const specialist = await prisma.specialist.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SpecialistUpdateManyArgs>(args: Prisma.SelectSubset<T, SpecialistUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Specialists and returns the data updated in the database.
   * @param {SpecialistUpdateManyAndReturnArgs} args - Arguments to update many Specialists.
   * @example
   * // Update many Specialists
   * const specialist = await prisma.specialist.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Specialists and only return the `id`
   * const specialistWithIdOnly = await prisma.specialist.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SpecialistUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SpecialistUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SpecialistPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Specialist.
   * @param {SpecialistUpsertArgs} args - Arguments to update or create a Specialist.
   * @example
   * // Update or create a Specialist
   * const specialist = await prisma.specialist.upsert({
   *   create: {
   *     // ... data to create a Specialist
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Specialist we want to update
   *   }
   * })
   */
  upsert<T extends SpecialistUpsertArgs>(args: Prisma.SelectSubset<T, SpecialistUpsertArgs<ExtArgs>>): Prisma.Prisma__SpecialistClient<runtime.Types.Result.GetResult<Prisma.$SpecialistPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Specialists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpecialistCountArgs} args - Arguments to filter Specialists to count.
   * @example
   * // Count the number of Specialists
   * const count = await prisma.specialist.count({
   *   where: {
   *     // ... the filter for the Specialists we want to count
   *   }
   * })
  **/
  count<T extends SpecialistCountArgs>(
    args?: Prisma.Subset<T, SpecialistCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SpecialistCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Specialist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpecialistAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SpecialistAggregateArgs>(args: Prisma.Subset<T, SpecialistAggregateArgs>): Prisma.PrismaPromise<GetSpecialistAggregateType<T>>

  /**
   * Group by Specialist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SpecialistGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SpecialistGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SpecialistGroupByArgs['orderBy'] }
      : { orderBy?: SpecialistGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SpecialistGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSpecialistGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Specialist model
 */
readonly fields: SpecialistFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Specialist.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SpecialistClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  media<T extends Prisma.Specialist$mediaArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Specialist$mediaArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MediaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  service_offerings<T extends Prisma.Specialist$service_offeringsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Specialist$service_offeringsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceOfferingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Specialist model
 */
export interface SpecialistFieldRefs {
  readonly id: Prisma.FieldRef<"Specialist", 'String'>
  readonly average_rating: Prisma.FieldRef<"Specialist", 'Decimal'>
  readonly is_draft: Prisma.FieldRef<"Specialist", 'Boolean'>
  readonly total_number_of_ratings: Prisma.FieldRef<"Specialist", 'Int'>
  readonly title: Prisma.FieldRef<"Specialist", 'String'>
  readonly slug: Prisma.FieldRef<"Specialist", 'String'>
  readonly description: Prisma.FieldRef<"Specialist", 'String'>
  readonly base_price: Prisma.FieldRef<"Specialist", 'Decimal'>
  readonly platform_fee: Prisma.FieldRef<"Specialist", 'Decimal'>
  readonly final_price: Prisma.FieldRef<"Specialist", 'Decimal'>
  readonly verification_status: Prisma.FieldRef<"Specialist", 'VerificationStatus'>
  readonly is_verified: Prisma.FieldRef<"Specialist", 'Boolean'>
  readonly duration_days: Prisma.FieldRef<"Specialist", 'Int'>
  readonly created_at: Prisma.FieldRef<"Specialist", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Specialist", 'DateTime'>
  readonly deleted_at: Prisma.FieldRef<"Specialist", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Specialist findUnique
 */
export type SpecialistFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Specialist
   */
  select?: Prisma.SpecialistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Specialist
   */
  omit?: Prisma.SpecialistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpecialistInclude<ExtArgs> | null
  /**
   * Filter, which Specialist to fetch.
   */
  where: Prisma.SpecialistWhereUniqueInput
}

/**
 * Specialist findUniqueOrThrow
 */
export type SpecialistFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Specialist
   */
  select?: Prisma.SpecialistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Specialist
   */
  omit?: Prisma.SpecialistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpecialistInclude<ExtArgs> | null
  /**
   * Filter, which Specialist to fetch.
   */
  where: Prisma.SpecialistWhereUniqueInput
}

/**
 * Specialist findFirst
 */
export type SpecialistFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Specialist
   */
  select?: Prisma.SpecialistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Specialist
   */
  omit?: Prisma.SpecialistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpecialistInclude<ExtArgs> | null
  /**
   * Filter, which Specialist to fetch.
   */
  where?: Prisma.SpecialistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Specialists to fetch.
   */
  orderBy?: Prisma.SpecialistOrderByWithRelationInput | Prisma.SpecialistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Specialists.
   */
  cursor?: Prisma.SpecialistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Specialists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Specialists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Specialists.
   */
  distinct?: Prisma.SpecialistScalarFieldEnum | Prisma.SpecialistScalarFieldEnum[]
}

/**
 * Specialist findFirstOrThrow
 */
export type SpecialistFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Specialist
   */
  select?: Prisma.SpecialistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Specialist
   */
  omit?: Prisma.SpecialistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpecialistInclude<ExtArgs> | null
  /**
   * Filter, which Specialist to fetch.
   */
  where?: Prisma.SpecialistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Specialists to fetch.
   */
  orderBy?: Prisma.SpecialistOrderByWithRelationInput | Prisma.SpecialistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Specialists.
   */
  cursor?: Prisma.SpecialistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Specialists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Specialists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Specialists.
   */
  distinct?: Prisma.SpecialistScalarFieldEnum | Prisma.SpecialistScalarFieldEnum[]
}

/**
 * Specialist findMany
 */
export type SpecialistFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Specialist
   */
  select?: Prisma.SpecialistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Specialist
   */
  omit?: Prisma.SpecialistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpecialistInclude<ExtArgs> | null
  /**
   * Filter, which Specialists to fetch.
   */
  where?: Prisma.SpecialistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Specialists to fetch.
   */
  orderBy?: Prisma.SpecialistOrderByWithRelationInput | Prisma.SpecialistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Specialists.
   */
  cursor?: Prisma.SpecialistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Specialists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Specialists.
   */
  skip?: number
  distinct?: Prisma.SpecialistScalarFieldEnum | Prisma.SpecialistScalarFieldEnum[]
}

/**
 * Specialist create
 */
export type SpecialistCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Specialist
   */
  select?: Prisma.SpecialistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Specialist
   */
  omit?: Prisma.SpecialistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpecialistInclude<ExtArgs> | null
  /**
   * The data needed to create a Specialist.
   */
  data: Prisma.XOR<Prisma.SpecialistCreateInput, Prisma.SpecialistUncheckedCreateInput>
}

/**
 * Specialist createMany
 */
export type SpecialistCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Specialists.
   */
  data: Prisma.SpecialistCreateManyInput | Prisma.SpecialistCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Specialist createManyAndReturn
 */
export type SpecialistCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Specialist
   */
  select?: Prisma.SpecialistSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Specialist
   */
  omit?: Prisma.SpecialistOmit<ExtArgs> | null
  /**
   * The data used to create many Specialists.
   */
  data: Prisma.SpecialistCreateManyInput | Prisma.SpecialistCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Specialist update
 */
export type SpecialistUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Specialist
   */
  select?: Prisma.SpecialistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Specialist
   */
  omit?: Prisma.SpecialistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpecialistInclude<ExtArgs> | null
  /**
   * The data needed to update a Specialist.
   */
  data: Prisma.XOR<Prisma.SpecialistUpdateInput, Prisma.SpecialistUncheckedUpdateInput>
  /**
   * Choose, which Specialist to update.
   */
  where: Prisma.SpecialistWhereUniqueInput
}

/**
 * Specialist updateMany
 */
export type SpecialistUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Specialists.
   */
  data: Prisma.XOR<Prisma.SpecialistUpdateManyMutationInput, Prisma.SpecialistUncheckedUpdateManyInput>
  /**
   * Filter which Specialists to update
   */
  where?: Prisma.SpecialistWhereInput
  /**
   * Limit how many Specialists to update.
   */
  limit?: number
}

/**
 * Specialist updateManyAndReturn
 */
export type SpecialistUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Specialist
   */
  select?: Prisma.SpecialistSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Specialist
   */
  omit?: Prisma.SpecialistOmit<ExtArgs> | null
  /**
   * The data used to update Specialists.
   */
  data: Prisma.XOR<Prisma.SpecialistUpdateManyMutationInput, Prisma.SpecialistUncheckedUpdateManyInput>
  /**
   * Filter which Specialists to update
   */
  where?: Prisma.SpecialistWhereInput
  /**
   * Limit how many Specialists to update.
   */
  limit?: number
}

/**
 * Specialist upsert
 */
export type SpecialistUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Specialist
   */
  select?: Prisma.SpecialistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Specialist
   */
  omit?: Prisma.SpecialistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpecialistInclude<ExtArgs> | null
  /**
   * The filter to search for the Specialist to update in case it exists.
   */
  where: Prisma.SpecialistWhereUniqueInput
  /**
   * In case the Specialist found by the `where` argument doesn't exist, create a new Specialist with this data.
   */
  create: Prisma.XOR<Prisma.SpecialistCreateInput, Prisma.SpecialistUncheckedCreateInput>
  /**
   * In case the Specialist was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SpecialistUpdateInput, Prisma.SpecialistUncheckedUpdateInput>
}

/**
 * Specialist delete
 */
export type SpecialistDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Specialist
   */
  select?: Prisma.SpecialistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Specialist
   */
  omit?: Prisma.SpecialistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpecialistInclude<ExtArgs> | null
  /**
   * Filter which Specialist to delete.
   */
  where: Prisma.SpecialistWhereUniqueInput
}

/**
 * Specialist deleteMany
 */
export type SpecialistDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Specialists to delete
   */
  where?: Prisma.SpecialistWhereInput
  /**
   * Limit how many Specialists to delete.
   */
  limit?: number
}

/**
 * Specialist.media
 */
export type Specialist$mediaArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Media
   */
  select?: Prisma.MediaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Media
   */
  omit?: Prisma.MediaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MediaInclude<ExtArgs> | null
  where?: Prisma.MediaWhereInput
  orderBy?: Prisma.MediaOrderByWithRelationInput | Prisma.MediaOrderByWithRelationInput[]
  cursor?: Prisma.MediaWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MediaScalarFieldEnum | Prisma.MediaScalarFieldEnum[]
}

/**
 * Specialist.service_offerings
 */
export type Specialist$service_offeringsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceOfferings
   */
  select?: Prisma.ServiceOfferingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceOfferings
   */
  omit?: Prisma.ServiceOfferingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceOfferingsInclude<ExtArgs> | null
  where?: Prisma.ServiceOfferingsWhereInput
  orderBy?: Prisma.ServiceOfferingsOrderByWithRelationInput | Prisma.ServiceOfferingsOrderByWithRelationInput[]
  cursor?: Prisma.ServiceOfferingsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ServiceOfferingsScalarFieldEnum | Prisma.ServiceOfferingsScalarFieldEnum[]
}

/**
 * Specialist without action
 */
export type SpecialistDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Specialist
   */
  select?: Prisma.SpecialistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Specialist
   */
  omit?: Prisma.SpecialistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SpecialistInclude<ExtArgs> | null
}
